// ── API contract (mirrors the FastAPI backend) ──────────────────────────────

export interface ChatRequest {
  session_id: string
  message: string
  user_id?: string
}

export interface ChatResponse {
  /** Markdown — rendered with react-markdown + remark-gfm. */
  response: string
  /** ["campo"] on success, [] on error — kept for API compatibility. */
  agents_used: string[]
  trace_url: string | null
  latency_ms: number
}

// ── Today screen ─────────────────────────────────────────────────────────────
// Mirrors GET /today-data. Every field can come back null/empty from the
// upstream football-data feed, so consumers must render defensively.

/** Normalized by the backend from football-data.org's wider vocabulary. */
export type MatchStatus = 'SCHEDULED' | 'LIVE' | 'FINISHED'

export interface TeamRef {
  name: string | null
  crest: string | null
}

export interface Match {
  /** football-data.org match id — the key for fetching this match's brief. */
  id: number | null
  utc_date: string | null
  home: TeamRef
  away: TeamRef
  home_score: number | null
  away_score: number | null
  status: MatchStatus
  venue: string | null
  group: string | null
}

export interface StandingRow {
  position: number | null
  team: TeamRef
  played: number | null
  points: number | null
  won: number | null
  draw: number | null
  lost: number | null
  goals_for: number | null
  goals_against: number | null
  goal_difference: number | null
}

export interface GroupStanding {
  group: string | null
  table: StandingRow[]
}

export interface TodayData {
  matches: Match[]
  recent_matches: Match[]
  standings: GroupStanding[]
  /** When the data was actually fetched upstream — may lag `now` by the cache TTL. */
  as_of: string
  /** Per-dataset failures; the arrays for failed datasets come back empty. */
  errors: Record<string, string> | null
}

// ── Pre-match briefs ─────────────────────────────────────────────────────────
// Mirrors GET /briefs/{match_id}. A brief is generated by the multi-agent
// pipeline (planner → research workers → writer → verifier) in the background;
// the UI polls until `status` leaves "generating".

export type BriefStatus = 'none' | 'generating' | 'ready' | 'failed'

export interface BriefClaim {
  claim: string
  verdict: 'supported' | 'unsupported'
  note: string
}

export interface Brief {
  match_id: number
  status: BriefStatus
  home?: string | null
  away?: string | null
  kickoff_utc?: string | null
  stage?: string | null
  venue?: string | null
  /** Markdown — present when status is "ready". */
  brief_markdown?: string
  /** Fact-check results from the verifier agent. */
  claims?: BriefClaim[]
  /** False when the verifier failed and the draft shipped unchecked. */
  verified?: boolean
  lanes_failed?: string[]
  generated_at?: string
  generation_seconds?: number
  /** Present when status is "failed". */
  error?: string
}

/** A single query↔answer exchange, tracked through its lifecycle. */
export interface Turn {
  id: string
  question: string
  answer: string | null
  latencyMs: number | null
  status: 'pending' | 'done' | 'error'
  errorMessage?: string
}
